In [48]:
#Data Loading and Data Storage

DATA LOADING AND DATA STORAGE

DATA SOURCE-> DATA LOAD->PANDAS DATAFRAME->DATA INSPECTION->DATA STORAGE->CSV,JSON,EXCEL, etccc

In [49]:
import pandas as pd

In [50]:
import os
print(os.getcwd())

/content

In [51]:
print(os.listdir())

['.config', 'students_pkl.pkl', 'students.parquet', 'students.csv', 'students.db-journal', 'students.txt', '.ipynb_checkpoints', 'sample_data']

CSV File

In [52]:
# Data to CSV
DataFrame={}

In [53]:
import pandas as pd

df = pd.DataFrame({
    "Employee_ID": ["E101", "E102", "E103", "E104", "E105", "E106", "E107"],
    "Name": ["Aman", "Priya", "Kunal", "Nisha", "Rohan", "Sneha", "Vikas"],
    "Department": ["IT", "HR", "Sales", "IT", "Finance", "HR", "Sales"],
    "City": ["Mathura", "Agra", "Delhi", "Noida", "Mathura", "Agra", "Delhi"],
    "Salary": [55000, 48000, 62000, 59000, 52000, 47000, 61000]
})

df.to_csv("employees.csv", index=False)

emp = pd.read_csv("employees.csv")

emp.to_csv("employees_pipe.txt", sep="|", index=False)
emp.to_csv("employees.tsv", sep="\t", index=False)

with pd.ExcelWriter("company.xlsx") as writer:
    emp.to_excel(writer, sheet_name="Employees", index=False)

In [54]:
# Correcting 'employees' to a string literal "employees.csv"
df = pd.read_csv("employees.csv")
display(df)

  Employee_ID   Name Department     City  Salary
0        E101   Aman         IT  Mathura   55000
1        E102  Priya         HR     Agra   48000
2        E103  Kunal      Sales    Delhi   62000
3        E104  Nisha         IT    Noida   59000
4        E105  Rohan    Finance  Mathura   52000
5        E106  Sneha         HR     Agra   47000
6        E107  Vikas      Sales    Delhi   61000

# Convert Data To excel file

In [55]:
excel_file_path = "employees.xlsx"
df.to_excel(excel_file_path, index=False, sheet_name="Employees_Data")
print({excel_file_path})
display(df)

{'employees.xlsx'}

  Employee_ID   Name Department     City  Salary
0        E101   Aman         IT  Mathura   55000
1        E102  Priya         HR     Agra   48000
2        E103  Kunal      Sales    Delhi   62000
3        E104  Nisha         IT    Noida   59000
4        E105  Rohan    Finance  Mathura   52000
5        E106  Sneha         HR     Agra   47000
6        E107  Vikas      Sales    Delhi   61000

In [56]:
# Convert data into JSON file
json_file_path = "employees.json"
df.to_json(json_file_path, orient="records", indent=4)

# Read back and print the content to verify
with open(json_file_path, 'r') as f:
    json_content = f.read()

print(json_content)

[
    {
        "Employee_ID":"E101",
        "Name":"Aman",
        "Department":"IT",
        "City":"Mathura",
        "Salary":55000
    },
    {
        "Employee_ID":"E102",
        "Name":"Priya",
        "Department":"HR",
        "City":"Agra",
        "Salary":48000
    },
    {
        "Employee_ID":"E103",
        "Name":"Kunal",
        "Department":"Sales",
        "City":"Delhi",
        "Salary":62000
    },
    {
        "Employee_ID":"E104",
        "Name":"Nisha",
        "Department":"IT",
        "City":"Noida",
        "Salary":59000
    },
    {
        "Employee_ID":"E105",
        "Name":"Rohan",
        "Department":"Finance",
        "City":"Mathura",
        "Salary":52000
    },
    {
        "Employee_ID":"E106",
        "Name":"Sneha",
        "Department":"HR",
        "City":"Agra",
        "Salary":47000
    },
    {
        "Employee_ID":"E107",
        "Name":"Vikas",
        "Department":"Sales",
        "City":"Delhi",
        "Salary":61000
    }
]

In [57]:
# convert the data into tab file
tab_file_path = "employees_tab.txt"
df.to_csv(tab_file_path, sep="\t", index=False)

# Read back and print the content to verify
with open(tab_file_path, 'r') as f:
    tab_content = f.read()

print(tab_content)

Employee_ID	Name	Department	City	Salary
E101	Aman	IT	Mathura	55000
E102	Priya	HR	Agra	48000
E103	Kunal	Sales	Delhi	62000
E104	Nisha	IT	Noida	59000
E105	Rohan	Finance	Mathura	52000
E106	Sneha	HR	Agra	47000
E107	Vikas	Sales	Delhi	61000

In [58]:
print("Shape:")
print(df.shape)

Shape:
(7, 5)

In [59]:
print("Columns:")
print(df.columns)

Columns:
Index(['Employee_ID', 'Name', 'Department', 'City', 'Salary'], dtype='object')

In [60]:
print("Data Type")
print(df.dtypes)

Data Type
Employee_ID    object
Name           object
Department     object
City           object
Salary          int64
dtype: object

In [61]:
print("First five Rows:")
df.head(6)

First five Rows:

  Employee_ID   Name Department     City  Salary
0        E101   Aman         IT  Mathura   55000
1        E102  Priya         HR     Agra   48000
2        E103  Kunal      Sales    Delhi   62000
3        E104  Nisha         IT    Noida   59000
4        E105  Rohan    Finance  Mathura   52000
5        E106  Sneha         HR     Agra   47000

In [62]:
df.tail(3)

  Employee_ID   Name Department     City  Salary
4        E105  Rohan    Finance  Mathura   52000
5        E106  Sneha         HR     Agra   47000
6        E107  Vikas      Sales    Delhi   61000

In [63]:
# Correcting the variable to 'emp' and saving it as a pipe-separated file
pipe_file_path = "employees_pipe.csv"
emp.to_csv(pipe_file_path, sep="|", index=False)

# Read back and print the content to verify
with open(pipe_file_path, 'r') as f:
    pipe_content = f.read()

print(pipe_content)

Employee_ID|Name|Department|City|Salary
E101|Aman|IT|Mathura|55000
E102|Priya|HR|Agra|48000
E103|Kunal|Sales|Delhi|62000
E104|Nisha|IT|Noida|59000
E105|Rohan|Finance|Mathura|52000
E106|Sneha|HR|Agra|47000
E107|Vikas|Sales|Delhi|61000

In [64]:
comma_file_path = "employees_comma.csv"
# Save the DataFrame with comma separation
emp.to_csv(comma_file_path, index=False)

# Correctly read and print the file contents to verify
with open(comma_file_path, 'r') as f:
    comma_content = f.read()

print(comma_content)

Employee_ID,Name,Department,City,Salary
E101,Aman,IT,Mathura,55000
E102,Priya,HR,Agra,48000
E103,Kunal,Sales,Delhi,62000
E104,Nisha,IT,Noida,59000
E105,Rohan,Finance,Mathura,52000
E106,Sneha,HR,Agra,47000
E107,Vikas,Sales,Delhi,61000

In [65]:
# Demonstrating skiprows, nrows, usecols, index_col, and names parameters in pd.read_csv

# 1. usecols:
print("usecols")
df_usecols = pd.read_csv('employees.csv', usecols=['Employee_ID', 'Name', 'Salary'])
display(df_usecols)

# 2. nrows
print("nrows")
df_nrows = pd.read_csv('employees.csv', nrows=3)
display(df_nrows)

# 3. skiprows:
print("skiprows")
df_skiprows = pd.read_csv('employees.csv', skiprows=[1, 2])
display(df_skiprows)

# 4. index_col:
print("index_col")
df_index = pd.read_csv('employees.csv', index_col='Employee_ID')
display(df_index)

# 5. names:
print("names")
custom_names = ['ID', 'Emp_Name', 'Dept', 'Location', 'Annual_Pay']
df_names = pd.read_csv('employees.csv', skiprows=1, names=custom_names)
display(df_names)

usecols

  Employee_ID   Name  Salary
0        E101   Aman   55000
1        E102  Priya   48000
2        E103  Kunal   62000
3        E104  Nisha   59000
4        E105  Rohan   52000
5        E106  Sneha   47000
6        E107  Vikas   61000

nrows

  Employee_ID   Name Department     City  Salary
0        E101   Aman         IT  Mathura   55000
1        E102  Priya         HR     Agra   48000
2        E103  Kunal      Sales    Delhi   62000

skiprows

  Employee_ID   Name Department     City  Salary
0        E103  Kunal      Sales    Delhi   62000
1        E104  Nisha         IT    Noida   59000
2        E105  Rohan    Finance  Mathura   52000
3        E106  Sneha         HR     Agra   47000
4        E107  Vikas      Sales    Delhi   61000

index_col

              Name Department     City  Salary
Employee_ID
E101          Aman         IT  Mathura   55000
E102         Priya         HR     Agra   48000
E103         Kunal      Sales    Delhi   62000
E104         Nisha         IT    Noida   59000
E105         Rohan    Finance  Mathura   52000
E106         Sneha         HR     Agra   47000
E107         Vikas      Sales    Delhi   61000

names

     ID Emp_Name     Dept Location  Annual_Pay
0  E101     Aman       IT  Mathura       55000
1  E102    Priya       HR     Agra       48000
2  E103    Kunal    Sales    Delhi       62000
3  E104    Nisha       IT    Noida       59000
4  E105    Rohan  Finance  Mathura       52000
5  E106    Sneha       HR     Agra       47000
6  E107    Vikas    Sales    Delhi       61000

In [66]:
#read the data from csv and how to write the data into csv

In [67]:
#Create TXT FILE,DATA ENTER | WRITE OPERATION
with open("students.txt","w") as file:
    file.write("Name,Department,Marks,city\n"),
    file.write("Astik,CSE,85,AGRA \n"),
    file.write("Abhiyank,IT,88,MATHURA \n"),
    file.write("Ayansh,IT,80,HATHRAS "),

In [68]:
with open("students.txt","r") as file:
 data=file.read()
print(data)

Name,Department,Marks,city
Astik,CSE,85,AGRA
Abhiyank,IT,88,MATHURA
Ayansh,IT,80,HATHRAS

SAVE THE .txt DATA into .CSV file

In [69]:

import pandas as pd;
df = pd.read_csv("students.txt")# Read the file into csv

df.to_csv("students.csv", index=False)# Conversion

df_verified = pd.read_csv("students.csv")
display(df_verified)

       Name Department  Marks      city
0     Astik        CSE     85     AGRA
1  Abhiyank         IT     88  MATHURA
2    Ayansh         IT     80  HATHRAS

In [70]:
# JSON File

In [71]:
# Excel file

In [72]:
# PICKEL
df=pd.DataFrame({
    "Name":["Aman","Ajay","Rakesh","Geeta"],
    "Marks":[80,90,50,40]
})
df

     Name  Marks
0    Aman     80
1    Ajay     90
2  Rakesh     50
3   Geeta     40

In [73]:
#Save the dataframe into pickle
df.to_pickle("students_pkl.pkl")

In [74]:
# Read the pickel file
student_pkl=pd.read_pickle("students_pkl.pkl")
student_pkl

     Name  Marks
0    Aman     80
1    Ajay     90
2  Rakesh     50
3   Geeta     40

WEB SCRAPPING

In [75]:
import requests
from bs4 import BeautifulSoup
url="https://www.amazon.com/"
page=requests.get(url)
soup=BeautifulSoup(page.text,"html.parser")

In [76]:
print(soup.title.text)

Amazon.com. Spend less. Smile more.

PARQUET

In [77]:
df_parquet=pd.DataFrame({
    "Name":["Aman","Ajay","Rakesh","Geeta"],
    "Marks":[80,90,50,40]
})
df_parquet

     Name  Marks
0    Aman     80
1    Ajay     90
2  Rakesh     50
3   Geeta     40

In [78]:
df_parquet.to_parquet("students.parquet",index=False)

In [79]:
# read the parquet file
df_parquet_file=pd.read_parquet("students.parquet")

In [80]:
print(df_parquet)

     Name  Marks
0    Aman     80
1    Ajay     90
2  Rakesh     50
3   Geeta     40

Sqlite

In [81]:
import sqlite3
conn=sqlite3.connect("students.db")

In [82]:
cursor=conn.cursor()
print("Database created Successfully")

Database created Successfully

In [83]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS student_table(

Name TEXT,
ROLL_NO INTEGER,
Marks INTEGER)



""")
print("Table is created successfully")

Table is created successfully

In [84]:
# write the data into table
import sqlite3
conn=sqlite3.connect("students.db")
cursor=conn.cursor()
cursor.execute(
    "INSERT INTO student_table VALUES(?,?,?)",
    ("Asmit",101,90)
)
cursor.execute(
    "INSERT INTO student_table VALUES(?,?,?)",
    ("Abhiyank",102,80)
)
cursor.execute(
    "INSERT INTO student_table VALUES(?,?,?)",
    ("Ayansh",103,70)
)

In [85]:
conn.commit()
print("Record inserted successfully ")
conn.close()

Record inserted successfully

In [86]:
# Retrive|read the data
import sqlite3
conn=sqlite3.connect("students.db")
cursor=conn.cursor()
cursor.execute("SELECT * FROM student_table")
result=cursor.fetchall()
for row in result:
    print(row)
conn.close()

('Asmit', 101, 90)
('Abhiyank', 102, 80)
('Ayansh', 103, 70)